namespace: "virt_lightning"
name: "virt_lightning"
version: "1.1.0"
readme: "README.md"
authors:
    - "Gonéri Le Bouder <goneri@lebouder.net>"
dependencies:
license:
    - "Apache-2"
tags:
  - cloud
  - libvirt
  - kvm
  - vm
repository: "https://github.com/virt-lightning/ansible-collection-virt-lightning/"
issues: "https://github.com/virt-lightning/ansible-collection-virt-lightning/issues"
